<?php // this is an autogenerated file - do not edit (created Sun, 30 Jan 2011 15:09:51 +0100)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'theseer\\fxsl\\fxslcallback' => '/src/fxslcallback.php',
            'theseer\\fxsl\\fxsltprocessor' => '/src/fxsltprocessor.php',
            'theseer\\fxsl\\fxsltprocessorexception' => '/src/fxsltprocessor.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
