<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'theseer\\fxsl\\fxslcallback' => '/fxslcallback.php',
                'theseer\\fxsl\\fxsltprocessor' => '/fxsltprocessor.php',
                'theseer\\fxsl\\fxsltprocessorexception' => '/fxsltprocessor.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd